### ISSUE TITLE
Pioneer3at model keeps sliding

### ISSUE THREAD

**Issue by eugene-katsevman** [MobileRobots/amr-ros-config#6] opened 2017-04-14 09:54 UTC
If I spawn the model, it starts sliding to the side after some time. Lowering delta T to 0.001 helps a little but, doesn't stop it.
Also, mass center and contacts are offset, is that ok?

![pioneer](https://cloud.githubusercontent.com/assets/5425080/25040357/7c9f63b0-2111-11e7-8c9b-b70562bd7d18.png)

**Comment by reedhedges** [comment] 2017-04-14 11:36
What version of Gazebo and the model is this?   How long until it starts "sliding"? Did you drive it first or does that happen with it just sitting still from its original position?  I think the mass should be centered, not sure why it shouldn't be.   I'll try to take a look at some point but if you or anyone else wants to take a look and let us know here if you see anything in the model itself or gazebo params that might be wrong that would be great.

**Comment by eugene-katsevman** [comment] 2017-04-14 11:40
it is gazebo 7.0.0 with ros kinetic and pioneer3at.

First I launch amr's empty world, then I launch spawn-pioneer3at. It starts moving visibly in 20-seconds or so. After a minute it has a steady sliding velocity of few mm per second. I haven't tried controlling it yet.

**Comment by eugene-katsevman** [comment] 2017-04-14 17:51
fdir1 is broken in gazebo up to 7 (https://bitbucket.org/osrf/gazebo/issues/463/ode-fdir1-parameter-broken   wheee this bug was where since 2013), causing pioneer to slide in y direction.
I have removed fdir1 from xacros and it seem to stand still now. Mass off-center was not causing it.

**Comment by reed-adept** [comment] 2017-04-14 18:33
OK I can just comment them out or remove them if that's equivalent to what you did?
(There are several parameters like that which are essentially undocumented -- neither in Gazebo nor ODE -- at least not in a way that was accessible/understandable by me.)

**Comment by eugene-katsevman** [comment] 2017-04-14 18:42
I commented them out, since they might come in handy gazebo 8 if fdir1 is fixed.

That is because Gazebo is using it's own fork of ODE, which has new features (like the enigmatic inertia reduction routine), not appearing on the upstream ODE. ODE mantainers (Oleh) won't bother to do a merge, nor Gazebo folks are willing. I did some code digging in last couple of weeks because of this situation, reviewing gazebo 8, sdformat and gazebo's ODE.

**Comment by reed-adept** [comment] 2017-04-14 20:15
removed fdir1 elements in commit f1e6eb1

**Comment by eugene-katsevman** [comment] 2017-04-17 18:01
mass offset seems to be made on purpose. May be batteries are on the side.

**Comment by reed-adept** [comment] 2017-04-17 18:12
No it was supposed to be towards the back a bit (due to batteries) -- x and y values were swapped. Fixed on master with 43715c9.

**Comment by eugene-katsevman** [comment] 2017-04-17 18:14
ah, okay

**Comment by eugene-katsevman** [comment] 2017-04-18 08:55
Should I close this issue? Or could you do it?

**Comment by eugene-katsevman** [comment] 2017-04-18 08:55
I'm not very familiar with this side of github

**Comment by reed-adept** [comment] 2017-04-18 13:34
If you have tested and verified the problem is fixed, you can indicate that in a comment or close it yourself, either is fine with me for this project.  (I also would eventually review open issues and close if I verify it's fixed.)

**Closed as completed** 2017-04-18 14:37 UTC
